    Analysis --> numpy , pandas
    Visualization --> pandas, matplotlib, seaborn

In [1]:
l = [10,20,30]

### Numpy

    scalar --> Having only magnitude no direction like 45
    vector --> It is the collection of scalar values --> 1D array
    
    Array???
        
        1. Homogenous (consist of data of same type)
        2. Indexing

    Benefit of using array in comparison with list is:
    1. Speed 
    2. memeory

In [2]:
import time

In [3]:
time.time()

1588132492.2680547

In [4]:
time.ctime()

'Wed Apr 29 09:25:37 2020'

In [5]:
time.strftime("%d-%m-%y")

'29-04-20'

In [6]:
time.strftime("%D-%M-%Y")

'04/29/20-26-2020'

In [7]:
help(time.strftime)

Help on built-in function strftime in module time:

strftime(...)
    strftime(format[, tuple]) -> string
    
    Convert a time tuple to a string according to a format specification.
    See the library reference manual for formatting codes. When the time tuple
    is not present, current time as returned by localtime() is used.
    
    Commonly used format codes:
    
    %Y  Year with century as a decimal number.
    %m  Month as a decimal number [01,12].
    %d  Day of the month as a decimal number [01,31].
    %H  Hour (24-hour clock) as a decimal number [00,23].
    %M  Minute as a decimal number [00,59].
    %S  Second as a decimal number [00,61].
    %z  Time zone offset from UTC.
    %a  Locale's abbreviated weekday name.
    %A  Locale's full weekday name.
    %b  Locale's abbreviated month name.
    %B  Locale's full month name.
    %c  Locale's appropriate date and time representation.
    %I  Hour (12-hour clock) as a decimal number [01,12].
    %p  Locale's equivalent o

In [8]:
import numpy as np

In [12]:
l1 =[i for i in range(10000)]
l2 = [i for i in range(10000)]
start = time.time()
m = [l1[i]*l2[i] for i in range(len(l1))]
end = time.time()
print("List time : ",end-start,"sec")
a1 = np.array(range(10000))
a2 = np.array(range(10000))
start = time.time()
a1*a2
end = time.time()
print("Array time : ",end-start,"sec")

List time :  0.0029921531677246094 sec
Array time :  0.0 sec


    Array can be of multiple dimensions 
        1D --> collection of scalar values
        2D --> collection of 1D array
        3D --> collecttion of 2D array
        

In [14]:
print(*range(100))

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99


In [15]:
a1 = np.array([1,2,3,4,5])

In [16]:
type(a1)

numpy.ndarray

In [17]:
a1

array([1, 2, 3, 4, 5])

In [18]:
a2 = np.array([i for i in range(20)])

In [19]:
a2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [20]:
a2.size

20

In [21]:
a2.ndim

1

In [22]:
a2.shape

(20,)

In [24]:
print("The size of the array is : ",a2.size)
print("The dimension of the array is : ",a2.ndim)
print("The shape of the array : ",a2.shape)

The size of the array is :  20
The dimension of the array is :  1
The shape of the array :  (20,)


In [25]:
a2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [26]:
a2.mean()

9.5

In [27]:
np.median(a2)

9.5

In [28]:
from statistics import mode

In [30]:
print(dir(a2))

['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_prepare__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__class__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rlshift_

In [29]:
mode(a2)

StatisticsError: no unique mode; found 20 equally common values

In [31]:
np.append(a2,[5,5])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19,  5,  5])

In [32]:
a2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [33]:
a2 = np.append(a2,[5,5])

In [34]:
a2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19,  5,  5])

In [35]:
a2.dtype

dtype('int32')

In [36]:
a3 = np.array(range(1000),dtype='int64')

In [37]:
a3

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [38]:
a2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19,  5,  5])

In [39]:
a2[0:6]

array([0, 1, 2, 3, 4, 5])

In [41]:
a2[5::2]

array([ 5,  7,  9, 11, 13, 15, 17, 19,  5])

In [42]:
a2[7::3]

array([ 7, 10, 13, 16, 19])

            2D array --> 2 dimensional array
            
                    12 10 15
                    23 45 67
                    34 89 90 
                    matrix --> m = 3 , n = 3

In [44]:
l2d = [[1,2,3],[4,5,6],[34,89,90]]
print(l2d)

[[1, 2, 3], [4, 5, 6], [34, 89, 90]]


    1 2 3
    4 5 6

In [45]:
arr2d = np.array(l2d)

In [46]:
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [34, 89, 90]])

In [48]:
print("The size of the array is : ",arr2d.size)   #m*n
print("The dimension of the array is : ",arr2d.ndim)
print("The shape of the array : ",arr2d.shape)

The size of the array is :  9
The dimension of the array is :  2
The shape of the array :  (3, 3)


In [49]:
l2d = [[1,2,3],[4,5,6],[34,89,90],[34,56,78]]
arr2d = np.array(l2d)
print("The size of the array is : ",arr2d.size)   #m*n
print("The dimension of the array is : ",arr2d.ndim)
print("The shape of the array : ",arr2d.shape)

The size of the array is :  12
The dimension of the array is :  2
The shape of the array :  (4, 3)


In [50]:
a1

array([1, 2, 3, 4, 5])

In [51]:
a2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19,  5,  5])

In [52]:
a2[:3]

array([0, 1, 2])

In [54]:
arr2d[3]

array([34, 56, 78])

            0   1  2
            10 20 30   0
            40 50 60   1
            70 80 90   2
            1  2  3    3

In [55]:
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [34, 89, 90],
       [34, 56, 78]])

In [56]:
arr2d[3]

array([34, 56, 78])

In [57]:
arr2d[2]

array([34, 89, 90])

In [58]:
l2d = [[1,2,3],[4,5,6],[34,89,90],[34,56,78]]

In [59]:
l2d[2][2]

90

In [60]:
arr2d[2,2]

90

    arr2d[row,col]

In [61]:
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [34, 89, 90],
       [34, 56, 78]])

In [62]:
from random import randint

In [63]:
l = [[randint(0,20) for i in range(5)]for _ in range(15)]

In [64]:
l

[[2, 17, 10, 18, 20],
 [14, 16, 2, 2, 15],
 [4, 17, 7, 16, 2],
 [2, 8, 17, 16, 10],
 [2, 7, 7, 17, 3],
 [7, 19, 2, 2, 5],
 [17, 19, 20, 0, 18],
 [7, 17, 10, 10, 17],
 [12, 6, 7, 20, 18],
 [5, 9, 12, 11, 9],
 [4, 12, 14, 1, 13],
 [10, 12, 2, 4, 11],
 [0, 3, 13, 12, 15],
 [11, 12, 4, 12, 0],
 [1, 7, 11, 8, 4]]

In [65]:
arr = np.array(l)

In [66]:
arr.shape

(15, 5)

In [67]:
arr.ndim

2

In [68]:
arr.dtype

dtype('int32')

In [69]:
print(arr)

[[ 2 17 10 18 20]
 [14 16  2  2 15]
 [ 4 17  7 16  2]
 [ 2  8 17 16 10]
 [ 2  7  7 17  3]
 [ 7 19  2  2  5]
 [17 19 20  0 18]
 [ 7 17 10 10 17]
 [12  6  7 20 18]
 [ 5  9 12 11  9]
 [ 4 12 14  1 13]
 [10 12  2  4 11]
 [ 0  3 13 12 15]
 [11 12  4 12  0]
 [ 1  7 11  8  4]]


In [70]:
arr[4,4]

3

In [71]:
arr[3:11,4]

array([10,  3,  5, 18, 17, 18,  9, 13])

In [72]:
arr[4::2,::2]

array([[ 2,  7,  3],
       [17, 20, 18],
       [12,  7, 18],
       [ 4, 14, 13],
       [ 0, 13, 15],
       [ 1, 11,  4]])

In [73]:
print(arr)

[[ 2 17 10 18 20]
 [14 16  2  2 15]
 [ 4 17  7 16  2]
 [ 2  8 17 16 10]
 [ 2  7  7 17  3]
 [ 7 19  2  2  5]
 [17 19 20  0 18]
 [ 7 17 10 10 17]
 [12  6  7 20 18]
 [ 5  9 12 11  9]
 [ 4 12 14  1 13]
 [10 12  2  4 11]
 [ 0  3 13 12 15]
 [11 12  4 12  0]
 [ 1  7 11  8  4]]


In [74]:
arr[3::3,1::3]

array([[ 8, 10],
       [19, 18],
       [ 9,  9],
       [ 3, 15]])

In [75]:
arr[::-1,::-1]

array([[ 4,  8, 11,  7,  1],
       [ 0, 12,  4, 12, 11],
       [15, 12, 13,  3,  0],
       [11,  4,  2, 12, 10],
       [13,  1, 14, 12,  4],
       [ 9, 11, 12,  9,  5],
       [18, 20,  7,  6, 12],
       [17, 10, 10, 17,  7],
       [18,  0, 20, 19, 17],
       [ 5,  2,  2, 19,  7],
       [ 3, 17,  7,  7,  2],
       [10, 16, 17,  8,  2],
       [ 2, 16,  7, 17,  4],
       [15,  2,  2, 16, 14],
       [20, 18, 10, 17,  2]])

In [76]:
arr[::-1]

array([[ 1,  7, 11,  8,  4],
       [11, 12,  4, 12,  0],
       [ 0,  3, 13, 12, 15],
       [10, 12,  2,  4, 11],
       [ 4, 12, 14,  1, 13],
       [ 5,  9, 12, 11,  9],
       [12,  6,  7, 20, 18],
       [ 7, 17, 10, 10, 17],
       [17, 19, 20,  0, 18],
       [ 7, 19,  2,  2,  5],
       [ 2,  7,  7, 17,  3],
       [ 2,  8, 17, 16, 10],
       [ 4, 17,  7, 16,  2],
       [14, 16,  2,  2, 15],
       [ 2, 17, 10, 18, 20]])

In [77]:
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [34, 89, 90],
       [34, 56, 78]])

In [78]:
arr2d.T

array([[ 1,  4, 34, 34],
       [ 2,  5, 89, 56],
       [ 3,  6, 90, 78]])

In [79]:
arr2d.mean()

33.5

In [80]:
np.median(arr2d)

20.0

In [81]:
mode(arr2d)

TypeError: unhashable type: 'numpy.ndarray'

In [82]:
arr2d.std()

34.371742269874346

In [83]:
arr2d.var()

1181.4166666666667

In [84]:
arr2d.ndim

2

#### 3D array

    collection of 2D array 
    3 2d array --> 2d array --> 3,3