In [1]:
import numpy as np

In [2]:
l = [
    [[1,2,3],
    [4,5,6],
    [7,8,9]],
    
    [[10,12,13],
    [14,15,16],
    [19,80,45]]
]

In [3]:
l

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 12, 13], [14, 15, 16], [19, 80, 45]]]

In [4]:
arr = np.array(l)

In [5]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 12, 13],
        [14, 15, 16],
        [19, 80, 45]]])

In [7]:
arr.shape   #2 --> 2d matrix , 3 --> rows, 3 --> cols

(2, 3, 3)

In [8]:
l = [
    [[1,2,3],
    [4,5,6],
    [7,8,9],
    [14,15,23]],
    
    [[10,12,13],
    [14,15,16],
    [19,80,45]]
]

In [9]:
arr = np.array(l)

In [10]:
arr

array([list([[1, 2, 3], [4, 5, 6], [7, 8, 9], [14, 15, 23]]),
       list([[10, 12, 13], [14, 15, 16], [19, 80, 45]])], dtype=object)

In [11]:
arr.shape

(2,)

In [12]:
l = [
    [[1,2,3],
    [4,5,6],
    [7,8,9],
    [14,15,23]],
    
    [[10,12,13],
    [14,15,16],
    [19,80,45],
    [34,45,56]]
]

In [13]:
arr = np.array(l)

In [14]:
arr.shape

(2, 4, 3)

In [15]:
arr.size

24

In [16]:
arr.ndim

3

In [17]:
arr.mean()

19.0

In [18]:
np.median(arr)

13.5

In [19]:
arr[3]

IndexError: index 3 is out of bounds for axis 0 with size 2

In [20]:
arr[1]

array([[10, 12, 13],
       [14, 15, 16],
       [19, 80, 45],
       [34, 45, 56]])

In [21]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [14, 15, 23]],

       [[10, 12, 13],
        [14, 15, 16],
        [19, 80, 45],
        [34, 45, 56]]])

In [24]:
arr[0]   #first 2d matrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [14, 15, 23]])

In [23]:
arr[1]  #second 2d matrix

array([[10, 12, 13],
       [14, 15, 16],
       [19, 80, 45],
       [34, 45, 56]])

    3D matrix
          array[2d_matrix,row,col]
          array[::,::,::]

In [26]:
arr[0,::,2]

array([ 3,  6,  9, 23])

In [27]:
arr[:,3,::]

array([[14, 15, 23],
       [34, 45, 56]])

In [28]:
arr[::-1,::-1,::-1]

array([[[56, 45, 34],
        [45, 80, 19],
        [16, 15, 14],
        [13, 12, 10]],

       [[23, 15, 14],
        [ 9,  8,  7],
        [ 6,  5,  4],
        [ 3,  2,  1]]])

In [31]:
from random import random,randint

In [30]:
random()

0.8264885292184988

In [32]:
randint(1,10)

3

In [34]:
np.random.randint(1,10,100)  #(start,stop,size)

array([7, 5, 6, 8, 6, 5, 6, 9, 6, 5, 3, 7, 2, 5, 2, 1, 9, 8, 5, 8, 9, 1,
       4, 9, 2, 4, 9, 9, 3, 6, 8, 1, 8, 7, 4, 1, 8, 4, 8, 2, 7, 7, 4, 1,
       8, 6, 6, 5, 6, 3, 3, 3, 5, 3, 1, 9, 6, 3, 6, 8, 1, 8, 9, 1, 9, 7,
       4, 2, 6, 5, 6, 1, 4, 3, 1, 5, 8, 8, 9, 4, 3, 5, 6, 9, 1, 7, 7, 2,
       3, 5, 3, 3, 8, 7, 4, 5, 7, 8, 6, 4])

In [35]:
arr1 = np.random.randint(1,10,60)

In [36]:
arr1

array([9, 1, 2, 1, 8, 9, 8, 7, 4, 9, 5, 9, 2, 5, 4, 2, 8, 6, 9, 8, 2, 3,
       8, 7, 2, 4, 4, 4, 9, 1, 6, 5, 2, 9, 1, 2, 2, 5, 4, 6, 8, 5, 9, 5,
       4, 7, 4, 4, 3, 4, 6, 5, 5, 2, 3, 4, 2, 9, 2, 3])

In [37]:
arr1.ndim

1

In [38]:
arr1.shape

(60,)

In [39]:
#reshape --> to change the shape of array like conversion from 1d to 2d and so on

In [44]:
arr2 = arr1.reshape(20,3)

In [46]:
arr2.ndim

2

In [48]:
arr2.shape

(20, 3)

In [42]:
arr1.reshape(3,20)

array([[9, 1, 2, 1, 8, 9, 8, 7, 4, 9, 5, 9, 2, 5, 4, 2, 8, 6, 9, 8],
       [2, 3, 8, 7, 2, 4, 4, 4, 9, 1, 6, 5, 2, 9, 1, 2, 2, 5, 4, 6],
       [8, 5, 9, 5, 4, 7, 4, 4, 3, 4, 6, 5, 5, 2, 3, 4, 2, 9, 2, 3]])

In [43]:
arr1

array([9, 1, 2, 1, 8, 9, 8, 7, 4, 9, 5, 9, 2, 5, 4, 2, 8, 6, 9, 8, 2, 3,
       8, 7, 2, 4, 4, 4, 9, 1, 6, 5, 2, 9, 1, 2, 2, 5, 4, 6, 8, 5, 9, 5,
       4, 7, 4, 4, 3, 4, 6, 5, 5, 2, 3, 4, 2, 9, 2, 3])

In [50]:
arr3 = arr1.reshape(2,10,3)

In [51]:
arr3

array([[[9, 1, 2],
        [1, 8, 9],
        [8, 7, 4],
        [9, 5, 9],
        [2, 5, 4],
        [2, 8, 6],
        [9, 8, 2],
        [3, 8, 7],
        [2, 4, 4],
        [4, 9, 1]],

       [[6, 5, 2],
        [9, 1, 2],
        [2, 5, 4],
        [6, 8, 5],
        [9, 5, 4],
        [7, 4, 4],
        [3, 4, 6],
        [5, 5, 2],
        [3, 4, 2],
        [9, 2, 3]]])

In [52]:
arr3.ndim

3

In [53]:
arr3.shape

(2, 10, 3)

In [54]:
print(arr3)

[[[9 1 2]
  [1 8 9]
  [8 7 4]
  [9 5 9]
  [2 5 4]
  [2 8 6]
  [9 8 2]
  [3 8 7]
  [2 4 4]
  [4 9 1]]

 [[6 5 2]
  [9 1 2]
  [2 5 4]
  [6 8 5]
  [9 5 4]
  [7 4 4]
  [3 4 6]
  [5 5 2]
  [3 4 2]
  [9 2 3]]]


In [55]:
arr3[-1,2::2,2]

array([4, 4, 6, 2])

    [[8,7,
    2,5,
    9,8,
    2,4]
    
    [2,5,
    9,5,
    3,4
    3,4]]

In [56]:
arr3[:2,:2,2]   #[0:2,0:2,2]

array([[2, 9],
       [2, 2]])

In [57]:
arr3[:,2::2,:2]  #[all,start::step,0:2]

array([[[8, 7],
        [2, 5],
        [9, 8],
        [2, 4]],

       [[2, 5],
        [9, 5],
        [3, 4],
        [3, 4]]])

In [58]:
arr3[1,1,1]  #2d matrix at index 1 and that row at index 1 and col at index 1

1

In [59]:
arr3[::,::,::]

array([[[9, 1, 2],
        [1, 8, 9],
        [8, 7, 4],
        [9, 5, 9],
        [2, 5, 4],
        [2, 8, 6],
        [9, 8, 2],
        [3, 8, 7],
        [2, 4, 4],
        [4, 9, 1]],

       [[6, 5, 2],
        [9, 1, 2],
        [2, 5, 4],
        [6, 8, 5],
        [9, 5, 4],
        [7, 4, 4],
        [3, 4, 6],
        [5, 5, 2],
        [3, 4, 2],
        [9, 2, 3]]])

    Benefit of array in comparison of list is there are operations that we can perform easily on array in comparison of 
    list

#### Operations

In [62]:
a1 = np.random.randint(1,10,10)
a2 = np.random.randint(1,20,10)

In [63]:
a1

array([3, 6, 4, 6, 2, 6, 6, 2, 3, 7])

In [64]:
a2

array([10,  6,  1, 12, 14,  8,  6, 10, 16, 15])

In [65]:
a1 + a2   #element wise addition

array([13, 12,  5, 18, 16, 14, 12, 12, 19, 22])

In [66]:
a1 - a2

array([ -7,   0,   3,  -6, -12,  -2,   0,  -8, -13,  -8])

In [67]:
a2 - a1

array([ 7,  0, -3,  6, 12,  2,  0,  8, 13,  8])

In [68]:
a1 + 5

array([ 8, 11,  9, 11,  7, 11, 11,  7,  8, 12])

In [69]:
a1*4

array([12, 24, 16, 24,  8, 24, 24,  8, 12, 28])

In [70]:
a1//9

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [71]:
a1/9

array([0.33333333, 0.66666667, 0.44444444, 0.66666667, 0.22222222,
       0.66666667, 0.66666667, 0.22222222, 0.33333333, 0.77777778])

In [72]:
a1/a2

array([0.3       , 1.        , 4.        , 0.5       , 0.14285714,
       0.75      , 1.        , 0.2       , 0.1875    , 0.46666667])

In [73]:
a1//a2

array([0, 1, 4, 0, 0, 0, 1, 0, 0, 0], dtype=int32)

In [74]:
a1%a2

array([3, 0, 0, 6, 2, 6, 0, 2, 3, 7], dtype=int32)

In [75]:
a1

array([3, 6, 4, 6, 2, 6, 6, 2, 3, 7])

In [76]:
a2

array([10,  6,  1, 12, 14,  8,  6, 10, 16, 15])

In [77]:
a2%a1

array([1, 0, 1, 0, 0, 2, 0, 0, 1, 1], dtype=int32)

In [79]:
a1*a2   #element wise multiplication

array([ 30,  36,   4,  72,  28,  48,  36,  20,  48, 105])

In [87]:
m1 = np.random.randint(1,10,10).reshape(2,5)

In [93]:
m1

array([[5, 2, 8, 7, 9],
       [9, 9, 6, 4, 9]])

In [89]:
m2 = np.random.randint(1,10,10).reshape(2,5)

In [91]:
m2

array([[3, 1, 2, 9, 8],
       [8, 2, 3, 7, 8]])

In [92]:
m2 + m1

array([[ 8,  3, 10, 16, 17],
       [17, 11,  9, 11, 17]])

In [95]:
m1*m2  #element wise

array([[15,  2, 16, 63, 72],
       [72, 18, 18, 28, 72]])

        [[ 1,2 ],     [ [3,4],            [ 1*3+2*5 , 1*4+2*6,
        [3,4]]         [5,6] ]  -->        3*4 + 4*5, 3*4+4*6]
         n1*m1           n2*m2   --->          2*2        
         Condition --> n1 = m2

In [96]:
m1@m2    #matrix multiplication

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 5)

In [97]:
m1 = np.array([[1,2],[3,4]])
m2 = np.array([[3,4],[5,6]])

In [98]:
m1

array([[1, 2],
       [3, 4]])

In [99]:
m2

array([[3, 4],
       [5, 6]])

In [100]:
m1@m2

array([[13, 16],
       [29, 36]])

In [101]:
m1 = np.random.randint(1,10,12).reshape(4,3)
m2 = np.random.randint(1,10,12).reshape(3,4)

In [103]:
m1

array([[9, 6, 4],
       [4, 4, 1],
       [4, 4, 9],
       [4, 4, 6]])

In [104]:
m2

array([[6, 3, 5, 5],
       [5, 6, 5, 8],
       [7, 8, 1, 7]])

In [102]:
m1@m2

array([[112,  95,  79, 121],
       [ 51,  44,  41,  59],
       [107, 108,  49, 115],
       [ 86,  84,  46,  94]])

In [105]:
###perform matrix multiplication by writing a python code

In [106]:
a1 

array([3, 6, 4, 6, 2, 6, 6, 2, 3, 7])

In [108]:
a2

array([10,  6,  1, 12, 14,  8,  6, 10, 16, 15])

In [110]:
a1>5

array([False,  True, False,  True, False,  True,  True, False, False,
        True])

In [111]:
a1<5

array([ True, False,  True, False,  True, False, False,  True,  True,
       False])

In [112]:
a1[a1>5]

array([6, 6, 6, 6, 7])

In [114]:
a1[a1<5]

array([3, 4, 2, 2, 3])

In [115]:
a2>5

array([ True,  True, False,  True,  True,  True,  True,  True,  True,
        True])

In [116]:
a2<5

array([False, False,  True, False, False, False, False, False, False,
       False])

In [117]:
a1[a2<5]

array([4])

In [118]:
a1[2]

4

In [123]:
a1[a1 == 7]

array([7])

In [126]:
(a2>5) & (a2<8)   #& --> and

array([False,  True, False, False, False, False,  True, False, False,
       False])

In [127]:
a2[(a2>5) & (a2<8)]   #& --> and

array([6, 6])

In [129]:
a2[(a2>5)  | (a2<8)]

array([10,  6,  1, 12, 14,  8,  6, 10, 16, 15])

In [130]:
a2[(a2>5)  | (a2>8)]

array([10,  6, 12, 14,  8,  6, 10, 16, 15])

In [134]:
np.ones(20).reshape(10,2) + 10

array([[11., 11.],
       [11., 11.],
       [11., 11.],
       [11., 11.],
       [11., 11.],
       [11., 11.],
       [11., 11.],
       [11., 11.],
       [11., 11.],
       [11., 11.]])